apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: spcruzaley/postgres-dou-challenge:latest
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /tmp
            name: postgredb
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - >
                  /tmp/script-db.sh
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - >
                  python2 /tmp/gmail.py
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      restartPolicy: Always
